#base.url=https://demo.guru99.com/V1/index.php
base.url=https://sucursalvirtual.metrogas.cl/ingreso/ingresar
api.base.url=https://demo.guru99.com
browser=chrome
headless=false
implicit.wait=10
explicit.wait=15
page.load.timeout=30